# markdownlint configuration for both markdownlint-cli and markdownlint-cli2
# Compatible format for pre-commit hooks

# Allow HTML elements (useful for GitHub-flavored markdown)
MD033: false

# Allow long lines (code blocks, links, etc.)
MD013: false

# Allow duplicate headers in different sections
MD024:
  siblings_only: true

# Allow bare URLs (auto-linking)
MD034: false
