---
# markdownlint-cli2 configuration
# This config works for both standalone usage and reviewdog integration
# Uses prettier preset as base with flexible customizations

extends:
  - markdownlint/style/prettier

config:
  # Allow HTML elements (useful for GitHub-flavored markdown)
  MD033: false
  
  # Allow long lines (code blocks, links, etc.)
  MD013: false
  
  # Allow duplicate headers in different sections
  MD024:
    siblings_only: true
  
  # Allow inline HTML
  MD033: false
  
  # Allow bare URLs (auto-linking)
  MD034: false

# Ignore patterns
ignores:
  - "node_modules/**"
  - ".git/**"
  - "**/.vscode/**"
  - "**/vendor/**"