add_newline = true

# right_format = """$time"""

[directory]
truncation_length = 2
truncate_to_repo = false

[time]
disabled = false
format = '⌚[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
time_range = "-"

[python]
pyenv_version_name = true

[memory_usage]
disabled = false
threshold = -1
