---
name: Lint All

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shfmt:
    name: run shfmt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          shfmt -i 2 -ci -w .
      - name: suggester / shfmt
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: shfmt
      - name: install shellcheck
        run: |
          scversion="latest"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-${scversion}/shellcheck" /usr/local/bin/
          rm -rf "shellcheck-${scversion}/shellcheck"
      - run: shellcheck -f diff $(shfmt -f .) | patch -p1
      - name: suggester / shellcheck
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: shellcheck
  markdownlint:
    name: run markdownlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install markdownlint-cli2
        run: |
          npm install -g markdownlint-cli2
          markdownlint-cli2 . || exit 0
      - name: suggester / markdownlint
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: markdownlint-cli2
