---
name: Lint All

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shfmt:
    name: run shfmt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          shfmt -i 2 -ci -w .
      - name: suggester / shfmt
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: shfmt
  markdownlint:
    name: run markdownlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm install -g markdownlint-cli2
      - name: suggester / markdownlint
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: markdownlint-cli2