---
name: Lint All

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: reviewdog
        uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        uses: reviewdog/action-shfmt@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
