---
name: Lint All

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v6.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: '\.tmpl$'
          DISABLE_LINTERS: BASH_EXEC,SHELL_SHFMT
